name: Cache Example Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cache_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up cache
      id: cache-step
      uses: actions/cache@v4
      with:
        path: ~/.cache
        key: cache-abb2437

    - name: prime-cache-abb2437
      run: echo "Cache result:${{ steps.cache-step.outputs.cache-hit }}"
